### ISSUE TITLE
Installer: switches for silent installation

### ISSUE THREAD

**Issue by thenktor** [msys2/msys2-installer#12]
Hi,

please add command line switches to the installer for a silent installation without user interaction. This is needed for software deployment. Or if this switches already exist add something to the documentation.

Thanks

**Comment by lazka** [comment]
>  In other words: Is there any drawback in just extracting the tar.xz myself?

There is no drawback besides some missing shortcuts in the start menu.

We'll try to switch to another installer framework in the future which supports silent installs, see #3

**Comment by lazka** [comment]
Looks like the qt installer now supports this somewhat: I've added some examples to https://github.com/msys2/msys2-installer/blob/master/README.md

Does this work for you? (or would have back then, if you no longer need this)

**Comment by thenktor** [comment]
Hi, I've changed my software deployment script to use the sfx.exe:
```powershell
# MSYS2
Write-Host "Install MSYS2"
$Installer = (Dir ${FileServer}\Deployment\installers\msys2\msys2-base-x86_64-*.sfx.exe | Sort CreationTime -Descending | Select Name -First 1).Name
$CWD = Get-Location
cd C:\
$SetupExitCode = (Start-Process -Wait -PassThru -NoNewWindow -FilePath "${FileServer}\Deployment\installers\msys2\${Installer}").ExitCode
Write-Host "Exit code: $SetupExitCode"
cd $CWD
```

So I do not need it anymore.
