### ISSUE TITLE
Nightly build link in readme is broken

### ISSUE THREAD

**Issue by 13steinj** [msys2/msys2-installer#17]
See also: m-ab-s/media-autobuild_suite/issues/1802

Link to nightly build in readme is broken due to the readme just using "-latest", however in the releases page a date is there. I don't understand why the date there exists, because it also is somehow not the date of the commit it is released from, nor the date the releases page claims the release was made (which is Jan 13). Is this a mess-up (fine; it happens) or did someone compromise a Github account and post a malicious executable as a release?

**Comment by lazka** [comment]
The last nightly run failed to upload some files, I've rerun it now.
