### ISSUE TITLE
What license is this under?

### ISSUE THREAD

**Issue by Duckle29** [msys2/msys2-installer#21]
What license is msys2-installer provided under? Is it BSD-3clause like the mingw-packages repo, or something else?

**Comment by lazka** [comment]
* The installer binary itself is GPL3 (since it's based on the qt5 installer framework).
* The included packages you can find here under "Dependencies", each with their respective license: https://packages.msys2.org/package/base?repo=msys&variant=x86_64

**Comment by Duckle29** [comment]
Okay thanks. That makes sense! :)
