### ISSUE TITLE
SFX archive - same setup - 2 machines - some projects won't compile on 2nd machine

### ISSUE THREAD

**Issue by TheArkive** [msys2/msys2-installer#33]
Several weeks ago (maybe a few months by now) I setup the sfx archive (msys2-base-x86_64-20210725.sfx.exe) on my system.  It took several minutes to go through several "key ring" updates.  That particular setup is still working fine on that machine.

I'm trying to setup msys2 on another PC now (windows), and it's completing in under a minute with several failures.

![image](https://user-images.githubusercontent.com/1229220/136713542-90f073c7-dd87-4052-b2ec-20f28090f0eb.png)

I'm wondering if this has to do with some of the certificate issues happening lately...

Anyways, the end result is that now I have projects that used to compile fine, but now some references are being reported as not declared in "this scope".

I was hoping to find a complete log in the msys2 root dir, but i was only able to take the screenshot during initial setup.

**Comment by jeremyd2019** [comment]
I'm not seeing any failure in the keyrings in that, just normal errors retrieving via WKD, but it then succeeds updating them via hkps://keyserver.ubuntu.com as expected

**Comment by jeremyd2019** [comment]
I don't see that defined in the mingw-w64 headers.  @Biswa96 ?

**Comment by TheArkive** [comment]
Thanks @Biswa96 !

It turns out, I was mistakenly using Build Tools compiler, not g++, my apologies.  massive facepalm here 🤦.  Just wanted to set the record straight.  The machine I thought that was "properly compiling" that #define ended up not compiling with the same err msg when using g++.

Those defines were in the Win10 sdk headers i was looking at 🤦.

Thanks again.
