### ISSUE TITLE
Latest msys2 installer flagged as malicious

### ISSUE THREAD

**Issue by elsaco** [msys2/msys2-installer#39]
The latest msys2 installer is flagged as malicious by `BitDefenderTheta` at https://virustotal.com:

![msys2_warning](https://user-images.githubusercontent.com/3933920/150217311-c75fe35e-7f9e-4e15-9f2c-c0bf52425195.png)

Also, the checksum on the website is different than the one from GitHub release:

`Verify with SHA256 checksum 5e188c7f3d564a2291d20b717712bb6f789a17b415e540f528c0025130ada4e1`

Is it safe to install `msys2-x86_64-20220118.exe`? Thx!

**Comment by lazka** [comment]
> Also, the checksum on the website is different than the one from GitHub release:

Oh, I used the checksum from the .sfx installer when updating the website. Thanks

**Comment by lazka** [comment]
For future reference, here is the result link: https://www.virustotal.com/gui/file/845cf6a7ea239b3ce3f5b26636a938f70a24b13baccb348119bdf5325ba0f211

Either way, false positives from some virus scanners happens regularly and there isn't much we can do really. If it makes you feel better you can use the previous installer release.

Feel free to still report your virustotal findings in the future.
