### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by kuehlc** [msys2/msys2-installer#42]
Whenever I try to download the installer (any version), it gets to like 90% and just fails to finish downloading. I've downloaded plenty of other things with no issue.

**Comment by afrxo** [comment]
Experiencing the exact same issue, Chrome throws "Failed - Needs authorization".

Reproduction:

- Navigate to https://www.msys2.org/#ray-donnelly-mingwandroid & download the GUI installer;
![Desktop Screenshot 2022 01 30 - 20 04 16 60](https://user-images.githubusercontent.com/80974275/151721149-79cfdd3b-c16d-4ac8-a9cb-052cc71bab03.png)

- Observe download failing:
![Screenshot 2022-01-30 234906](https://user-images.githubusercontent.com/80974275/151721214-3809db66-bc91-4233-b658-18432e880741.png)

**Comment by afrxo** [comment]
Experiencing the exact same issue, Chrome throws "Failed - Needs authorization".

Reproduction:

- Navigate to https://www.msys2.org/#ray-donnelly-mingwandroid & download the GUI installer;


- Observe download failing:
![Screenshot 2022-01-30 234906](https://user-images.githubusercontent.com/80974275/151721214-3809db66-bc91-4233-b658-18432e880741.png)

**Comment by lazka** [comment]
Hard to say why. According to https://tooomm.github.io/github-release-stats/?username=msys2&repository=msys2-installer it gets downloaded a lot without any issue (I assume).

Maybe some antivirus thingy? Does it work in Firefox?

Does downloading from our repo server work? https://repo.msys2.org/distrib/x86_64/

**Comment by lazka** [comment]
I assume this fix itself now. If not please try to answer my questions above.

thanks
