### ISSUE TITLE
how to use msys2 pacman install python 3.8 dependencies?

### ISSUE THREAD

**Issue by lpiert** [msys2/msys2-installer#43]
First of all, I especially like the way pacman manages packages, but the latest msys2 uses pacman to install python by default to 3.9. because python3.9 not support jpype, so  manually installs python3.8 , After installing through .pkg.tar.zst, pip, numpy, etc. will fail. Why can't I allow specifying a version when doing "pacman -S mingw-w64-i686-python"? For example "pacman -S mingw-w64-i686-python3.8" ? I like this style as pacman but it also brings a lot of troubles. I like the flexibility of cygwin and envy the simplicity of pacman. lol

**Comment by lazka** [comment]
I agree that it would be nice, but that would mean that we'd need to maintain a separate package for each Python version, and that's a lot of work.

**Comment by lazka** [comment]
There is plan to create an archive so you could install older packages, https://github.com/msys2/msys2-archive but nothing is done yet.

It's unlikely we'll support multiple Python versions (just python+pip would be possible, but not all packages)
