### ISSUE TITLE
how to upgrade the msys2 installation

### ISSUE THREAD

**Issue by ccyykkcyk** [msys2/msys2-installer#45]
when the new msys2-installer release, I try to run the new installer, but it can't upgrade my old installation, and ``pacman -Syu`` do nothing, what should i do?

**Comment by Biswa96** [comment]
> and `pacman -Syu` do nothing

Can you provide the output of that command please?

**Comment by ccyykkcyk** [comment]
![image](https://user-images.githubusercontent.com/91893497/166637238-5aefa280-7bb4-4aab-baac-171e966d5a30.png)

it say nothing to do, but the version is old in control panel
![image](https://user-images.githubusercontent.com/91893497/166637576-fa51c733-9b8d-4e2f-99ac-c58f41ec371e.png)

**Comment by Biswa96** [comment]
> it say nothing to do

Then there nothing to update or upgrade.

> but the version is old in control panel

That version number in Control Panel is just the version number of the installer and it has nothing to with packages version.

**Comment by ccyykkcyk** [comment]
Does this mean I don't need to do anything when a new installer is released?

**Comment by Biswa96** [comment]
Nope. Just update the packages regularly as usual.

**Comment by ccyykkcyk** [comment]
Ok, thank you for your help!
