### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by stevefan1999-personal** [msys2/msys2-installer#46]
We could leverage the clangarm64 repo, but that means most of the MinGW ecosystem around GCC won't be available sometime

**Comment by lazka** [comment]
What are you suggesting?

**Comment by stevefan1999-personal** [comment]
@lazka I was looking to install MSYS2 on my ARM Windows box but so far I only saw x86/x64 options only. This I know is a pretty hard problem since MinGW doesn't yet support Windows on ARM far as I know

**Comment by lazka** [comment]
MSYS2 works fine with the x64 emulation provided by Windows. For everything else see https://github.com/msys2/MSYS2-packages/discussions/2889

**Comment by stevefan1999-personal** [comment]
@lazka sure, but on the Snapdragon 7c, the performance is terrible. Running the native x64 powershell took a minute to load

**Comment by lazka** [comment]
I don't know if that works on arm64 too (I don't have any hardware), but adding C:\msys64 to the defender exclusion list should speed things up a lot.

**Comment by lazka** [comment]
I've created a page for arm64: https://www.msys2.org/wiki/arm64/

Nothing new, but we'll update things there if they change.
