### ISSUE TITLE
Winget integration is broken

### ISSUE THREAD

**Issue by Danik1601** [msys2/msys2-installer#47]
Recently I tried to update all my installed Win32 apps using Microsoft's [Windows Package Manager](https://docs.microsoft.com/en-us/windows/package-manager/) aka "Winget" and I discovered this (first screenshot). MSYS2 does not update by any means.
At first, I thought that the installer somehow is not working correctly with Winget but then I discovered [this issue](https://github.com/msys2/msys2-installer/issues/45) and realized that the whole version reporting system is broken.
Please consider fixing this since that MSYS2 "package" alone breaks the whole Winget experience. 
On the second screenshot I tried to update MSYS2 using the newer .exe manually.

P.S. I have some conjectures on why this problem is not still fixed since this is very obvious and easy to find problem and I am almost certainly not the first one discovering this. My thoughts is that if you fix this, something else may break (I am really only guessing). If so, I propose very strange quirk to resolve issues with Winget. @Biswa96 in the above mentioned issue [said](https://github.com/msys2/msys2-installer/issues/45#issuecomment-1117004221):

> That version number in Control Panel is just the version number of the installer and it has nothing to with packages version.

If that is correct, then this might work out. As you may see on third screenshot, I have GOG Galaxy installed on my machine. The GOG version is not reported to Windows OS so Winget does not know which version is installed. Since Winget 1.3 [by default will be hiding packages that does not report their version](https://github.com/microsoft/winget-cli/pull/1765), you may just make the installer stop reporting it's version to Windows just like GOG does.
Please use this quirk only in case of emergency 😂.

![image](https://user-images.githubusercontent.com/17238959/169622092-7a6cecd8-74fe-4c2d-b155-412949aabbd6.png)

![image](https://user-images.githubusercontent.com/17238959/169624499-d4f48663-2a56-4b0d-979f-f4508b53e76d.png)

![image](https://user-images.githubusercontent.com/17238959/169623431-29d2a02a-2d7f-4811-86c1-25c8bf3ab6c2.png)

**Comment by Biswa96** [comment]
> realized that the whole version reporting system is broken.

It's not broken. The version you're seeing in winget output is the the msys2 installer version. If you update packages in msys2 with pacman it's enough.

**Comment by Danik1601** [comment]
> It's not broken. The version you're seeing in winget output is the the msys2 installer version. If you update packages in msys2 with pacman it's enough.

Well, than why the installer even reporting it's version number? It breaks some things (e.g. Winget)

**Comment by Biswa96** [comment]
> why the installer even reporting it's version number?

Is there any other way to know if the msys2 installer is newer or older?

**Comment by MehdiChinoune** [comment]
msys2 should be removed from winget databases.
The one who added it doesn't know about MSYS2 at all.

**Comment by lazka** [comment]
It's probably best to file an issue with winget. If they have any ideas on how we could improve the installer to better integrate it into their update process then we'd be happy to have a look.

**Comment by Danik1601** [comment]
> Is there any other way to know if the msys2 installer is newer or older?

What is the point if it performs one-time installation and then not getting updates forever after. Am I misunderstanding the concept?

**Comment by MehdiChinoune** [comment]
> > Is there any other way to know if the msys2 installer is newer or older?
> 
> What is the point if it performs one-time installation and then not getting updates forever after. Am I misunderstanding the concept?

MSYS2 has its own package manager called `pacman`.
To update packages open any MSYS2 shell and write:
```
pacman -Syu
```

**Comment by Danik1601** [comment]
> MSYS2 has its own package manager called `pacman`.
To update packages open any MSYS2 shell and write:
> 
> ```
> pacman -Syu
> ```

I installed the older version and updated it using pacman just like you said. It still reports the older version to the OS (first screenshot). No other updates are available, everything is up to date (second screenshot). Now I am completely lost and do not understand anything. As far as see (maybe not far enough) you just proved me that it is completely useless to report version number to the OS.

![image](https://user-images.githubusercontent.com/17238959/169653422-c3919d67-0dcb-46df-98b2-15dd2a1633e1.png)


![image](https://user-images.githubusercontent.com/17238959/169653414-d8f40c62-9832-45fd-8697-2f8b6fed4c0e.png)

**Comment by MehdiChinoune** [comment]
Your MSYS2 is up to date, the msys2-version you see is the version of the installer.

**Comment by Danik1601** [comment]
> Your MSYS2 is up to date, the msys2-version you see is the version of the installer.

Ok, then why do I need to know the installer version? Is it possible to update it without deleting the old version first?

> msys2 should be removed from winget databases.

I disagree since it is very useful in scripts and automation. For example I have all my installed programs written as list of Winget commands that I just copy-paste on my new machines, virtual machines or after system reinstallation.
