### ISSUE TITLE
gpg keys bitdefender detecting virus

### ISSUE THREAD

**Issue by robo-loki** [msys2/msys2-installer#48]
Hi all-

at https://www.msys2.org/ download link

[0xf7a49b0ec](http://keyserver.ubuntu.com/pks/lookup?search=0x0ebf782c5d53f7e5fb02a66746bd761f7a49b0ec&fingerprint=on&op=vindex)

I go to here: https://www.msys2.org/dev/keyring/#master-key-signatures

I don't see that key at the first link at ubuntu.keyserver.com. Just trying to track down if there is a bad key.
I didn't get a virus but am trying to find out where it is coming from so I don't 
install with the software causing it.

I can't verify. Can someone help me? 

THANKS,
roboloki

**Comment by lazka** [comment]
The installer signing key is my personal one, not the packaging or master key.

As for bitdefender etc. We get false positives all the time, not much we can do about it.
