### ISSUE TITLE
Error when executing 'pacman -Syu'

### ISSUE THREAD

**Issue by AbdesamedBendjeddou** [msys2/msys2-installer#49]
after installing MSYS2 in the default folder and running it, executing the command 'pacman -Syu' result in the following error:
'error: no usable package repositories configured.'

Windows 11 x64 build 22621.160
Msys2 installer for Windows release of 2022-06-03

**Comment by MehdiChinoune** [comment]
does `/etc` folder contain a file named `pacman.conf`

**Comment by lazka** [comment]
The output of `pacman -Suy --debug` might also be helpful.

**Comment by AbdesamedBendjeddou** [comment]
sorry forget to come here after finding the issue. the reason of this error was that the installer hasn't been downloaded correctly cause of spotty internet. redownloading the file fixed the issue

**Comment by lazka** [comment]
Thanks
