### ISSUE TITLE
Provided SHA256 checksum does not match

### ISSUE THREAD

**Issue by Yamahari** [msys2/msys2-installer#6]
Did you forget to update the provided checksum on the msys2.org website?

with windows certutil I got "2dacadcc70cc122054e60914cbc6b689f685bef5713915a90f4185dd9da7954e" instead of the provided "a4fd4e48f506618ee5eb8bbd439c2b37433edff5ada04c72db82ccbdbca35cd7" for the "msys2-x86_64-20200602" version.

**Comment by lazka** [comment]
With sha256sum.exe I get `a4fd4e48f506618ee5eb8bbd439c2b37433edff5ada04c72db82ccbdbca35cd7`
