### ISSUE TITLE
Debug information of msys-2.0.dll available?

### ISSUE THREAD

**Issue by bernhardu** [msys2/msys2-installer#62]
Is there possibly a build artifact available which contains the debug information
for msys-2.0.dll or an unstripped version of it?
I tried to have a look at a bug report against wine for the [msys2-installer](https://github.com/msys2/msys2-installer/releases/download/2023-03-18/msys2-x86_64-20230318.exe), and now I receive a crash inside msys-2.0.dll, and debug information would help to tell if that is an already known wine issue.

I also failed to find instructions to rebuild the msys-2.0.dll
from the msys2-runtime repository, I hope I not just have overlooked it?

**Comment by lazka** [comment]
On a phone right now so cant check, but the build artifacts here might contain debug info: https://github.com/msys2/msys2-runtime/actions/runs/4652041499

**Comment by bernhardu** [comment]
Just a short note if someone needs other debug information for msys-2.0.dll or other dlls.
In the end I find it quite easy to just rebuild it:
```
nano /etc/makepkg.conf
# change OPTIONS line to ... !strip ... debug
pacman --sync git patch binutils
git clone "https://github.com/msys2/MSYS2-packages"
cd MSYS2-packages/msys2-runtime
makepkg -sCLf
```
This worked quite nice on a fresh installation, and makes sure that the binary matches the dll.
(for other dlls needed some additional gpg keys e.g. libassuan: `gpg --recv-key 528897B826403ADA`.)

**Comment by lazka** [comment]
you don't need to change makepkg.conf, you can also add "!strip debug" to options in the respective PKGBUILD, see https://wiki.archlinux.org/title/Debugging/Getting_traces#Compilation_options
