### ISSUE TITLE
MSYS2 安装程序出错

### ISSUE THREAD

**Issue by fanyufan** [msys2/msys2-installer#67]
How to deal this? Thanks.
![image](https://github.com/msys2/msys2-installer/assets/9214771/346732cf-186e-4a9f-ad62-896f0c55ba99)

**Comment by Biswa96** [comment]
Exclude the `D:\msys64` directory in the running antivirus program like Windows Defender.

**Comment by fanyufan** [comment]
> Exclude the `D:\msys64` directory in the running antivirus program like Windows Defender.

Thanks

**Comment by Biswa96** [comment]
Fee free to close the issue if that fixed it.
