### ISSUE TITLE
Github communication error

### ISSUE THREAD

**Issue by becauro** [msys2/msys2-installer#71]
Hi, guys!

I installed the 2023-07-18 version, but that is not working to communicate with github

When I type ssh -T git@github.com I get authentication error

![git-error-in-msys2](https://github.com/msys2/msys2-installer/assets/61303294/67c45546-0cd9-41f3-a163-84d0ac81101c)

Notes:

* I tested it in both: MinGW64 and UCRT64 environments
* I tested it with both: rsa and ed15519 algorithms
* I tested it in both mode: normal and adm user
* In [Git for Windows](https://github.com/git-for-windows/) software everything works

Notes (off-topic):

* The discord invite link is expired

**Comment by Biswa96** [comment]
Type 'yes' after that question.

**Comment by sskras** [comment]
@becauro commented [7 hours ago](https://github.com/msys2/msys2-installer/issues/71#issue-1897484016):

> When I type ssh -T [git@github.com](mailto:git@github.com) I get authentication error

[...]

> * In [Git for Windows](https://github.com/git-for-windows/) software everything works

It does not for me with vanilla **Git for Windows** setup:

![image](https://github.com/msys2/msys2-installer/assets/7887758/a854a307-340a-4cf6-8f2b-28ee38503535)

I guess if you are remove the GitHub lines from `.ssh/known_hosts` like this (eg. by renaming the file):
```
github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
```
... then it would fail for you too.

So, essentially it's what @Biswa96 said :)

**Comment by becauro** [comment]
> Type 'yes' after that question.

Yes.. My bad.
Thank you!

**Comment by becauro** [comment]
Thank you, @Biswa96  
Yes, @sskras
