### ISSUE TITLE
My Antivirus kills C:\msys64\usr\bin\install-info.exe

### ISSUE THREAD

**Issue by cannnAvar** [msys2/msys2-installer#74]
I was done with my setup everything was good. Then I run
```pacman -Syu``` 
Antivirius program alert `C:\msys64\usr\bin\install-info.exe` is trojen 
after reboot pacman can't lock database

**Comment by lazka** [comment]
Report it to your antivirus vendor. There is nothing we can do about it.

**Comment by cannnAvar** [comment]
thx anyway

**Comment by lazka** [comment]
In many cases antivirus allows to exclude certain directories from being scanned. You could set up such an exception for `C:\msys64`.
