### ISSUE TITLE
stuck updating trust database

### ISSUE THREAD

**Issue by heavyk** [msys2/msys2-installer#75]
I'm behind an http proxy. it is defined in env vars as `http_proxy` and `https_proxy`, but the installer is stuck for quite a while now (looks like no timeout either)

```
Preparing the installation...

Preparing to unpack components...

Unpacking components...
Extracting "20231026msys64.7z"
Done

Installing component MSYS2
Copying skeleton files.
These files are for the users to personalise their msys2 experience.

They will never be overwritten nor automatically updated.


'./.bashrc' -> '/home/Kenny/.bashrc'

'./.bash_logout' -> '/home/Kenny/.bash_logout'

'./.bash_profile' -> '/home/Kenny/.bash_profile'

'./.profile' -> '/home/Kenny/.profile'

'C:\Windows\system32\drivers\etc\hosts' -> '/etc/hosts'

'C:\Windows\system32\drivers\etc\protocol' -> '/etc/protocols'

'C:\Windows\system32\drivers\etc\services' -> '/etc/services'

'C:\Windows\system32\drivers\etc\networks' -> '/etc/networks'

==> Generating pacman master key. This may take some time.

==> Updating trust database...

==> Appending keys from msys2.gpg...

==> Locally signing trusted keys in keyring...

  -> Locally signed 5 keys.

==> Importing owner trust values...

==> Disabling revoked keys in keyring...

  -> Disabled 4 keys.
==> Updating trust database...
```

**Comment by lazka** [comment]
Hm, this is before `gpg --batch --check-trustdb`. I don't know how to give gnupg a timeout.

You could use the archives instead of the installer: https://github.com/msys2/msys2-installer/releases

https://www.msys2.org/docs/installer/#whats-the-difference-between-the-installer-and-the-archives

**Comment by heavyk** [comment]
so, the next day I redownloaded the installer and it magically worked. I'm not really sure why it failed then afterward worked. I didn't restart my computer (it slept) and everything else is the same. closing this for now. let me know if you want me to look into it further. cheers!

**Comment by lazka** [comment]
ok, thanks for the update

**Comment by vinbo** [comment]
I met exactly the same problem... What should I do?

**Comment by Biswa96** [comment]
> I met exactly the same problem... What should I do?

* allow network connection from msys2 installation directory in network firewall.
* use latest installer.
* make sure antivirus programs are not interfering with msys2 processes.
etc.

**Comment by vinbo** [comment]
> I met exactly the same problem... What should I do? Everything here https://community.vcvrack.com/t/msys2-wont-install/19271/5 does not work.
> 
> follow @lazka 's advice, I use archives instead, but at the login shell step, same thing happed to the updating trusting datebase, screen keep rolling:
> 
> ==> Updating trust database... gpg: marginals needed: 3 completes needed: 1 trust model: pgp gpg: depth: 0 valid: 1 signed: 5 trust: 0-, 0q, 0n, 0m, 0f, 1u gpg: depth: 1 valid: 5 signed: 7 trust: 0-, 0q, 0n, 5m, 0f, 0u gpg: depth: 2 valid: 4 signed: 2 trust: 4-, 0q, 0n, 0m, 0f, 0u gpg: next trustdb check due at 2024-04-10 gpg: error retrieving '[alexey.pawlow@gmail.com](mailto:alexey.pawlow@gmail.com)' via WKD: Connection timed out gpg: error reading key: Connection timed out gpg: refreshing 1 key from hkps://keyserver.ubuntu.com gpg: key F40D263ECA25678A: "Alexey Pavlov (Alexpux) [alexey.pawlow@gmail.com](mailto:alexey.pawlow@gmail.com)" not changed gpg: Total number processed: 1 gpg: unchanged: 1 gpg: error retrieving '[david.macek.0@gmail.com](mailto:david.macek.0@gmail.com)' via WKD: Connection timed out gpg: error reading key: Connection timed out gpg: refreshing 1 key from hkps://keyserver.ubuntu.com gpg: key 790AE56A1D3CFDDC: "David Macek (MSYS2 master key) [david.macek.0@gmail.com](mailto:david.macek.0@gmail.com)" not changed gpg: Total number processed: 1 gpg: unchanged: 1
> 
> But if i just quit, and double clip msys2.exe again, then I get the prompt interface directly, so, my question is: what exactly did I miss? Did I installed completely?

The second time, I waited long enough, and msys2 tried enough times and get tired and said "completely".... really?

==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabled 4 keys.
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   5  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   5  signed:   7  trust: 0-, 0q, 0n, 5m, 0f, 0u
gpg: depth: 2  valid:   4  signed:   2  trust: 4-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2024-04-10
gpg: error retrieving 'alexey.pawlow@gmail.com' via WKD: Connection timed out
gpg: error reading key: Connection timed out
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key F40D263ECA25678A: "Alexey Pavlov (Alexpux) <alexey.pawlow@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: error retrieving 'david.macek.0@gmail.com' via WKD: Connection timed out
gpg: error reading key: Connection timed out
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key 790AE56A1D3CFDDC: "David Macek (MSYS2 master key) <david.macek.0@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: error retrieving 'martellmalone@gmail.com' via WKD: Connection timed out
gpg: error reading key: Connection timed out
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key DA7EF2ABAEEA755C: "Martell Malone (martell) <martellmalone@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: error retrieving 'reiter.christoph@gmail.com' via WKD: Connection timed out
gpg: error reading key: Connection timed out
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key 755B8182ACD22879: "Christoph Reiter (MSYS2 master key) <reiter.christoph@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: error retrieving 'icquinteiro@gmail.com' via WKD: Connection timed out
gpg: error reading key: Connection timed out
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key 9F418C233E652008: "Ignacio Casal Quinteiro <icquinteiro@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: error retrieving 'mingw.android@gmail.com' via WKD: Connection timed out
gpg: error reading key: Connection timed out
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key BBE514E53E0D0813: "Ray Donnelly (MSYS2 Developer - master key) <mingw.android@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: error retrieving 'alexpux@gmail.com' via WKD: Connection timed out
gpg: error reading key: Connection timed out
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key 5F92EFC1A47D45A1: "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: error retrieving 'david.macek.0@gmail.com' via WKD: Connection timed out
gpg: error reading key: Connection timed out
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key 974C8BE49078F532: "David Macek <david.macek.0@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: error retrieving 'reiter.christoph@gmail.com' via WKD: Connection timed out
gpg: error reading key: Connection timed out
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key FA11531AA0AA7F57: "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: error retrieving 'me@martellmalone.com' via WKD: No name
gpg: error reading key: No name
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key 794DCF97F93FC717: "Martell Malone (martell) <me@martellmalone.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: error retrieving 'martellmalone@gmail.com' via WKD: Connection timed out
gpg: error reading key: Connection timed out
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key D595C9AB2C51581E: "Martell Malone (MSYS2 Developer) <martellmalone@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: error retrieving 'mingw.android@gmail.com' via WKD: Connection timed out
gpg: error reading key: Connection timed out
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key 4DF3B7664CA56930: "Ray Donnelly (MSYS2 Developer) <mingw.android@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Initial setup complete. MSYS2 is now ready to use.

Is this normal?

**Comment by vinbo** [comment]
> > I met exactly the same problem... What should I do?
> 
>     * allow network connection from msys2 installation directory in network firewall.
> 
>     * use latest installer.
> 
>     * make sure antivirus programs are not interfering with msys2 processes.
>       etc.

Thanks, not work, not work for those in the link I attached either.

**Comment by zweber21** [comment]
Pretty similar solution to the firewall settings, but I had the same issue. I fixed it by changing my network in Windows from public to private.
