### ISSUE TITLE
Unable to start installer inside docker using image mcr.microsoft.com/windows/servercore:1809-amd64

### ISSUE THREAD

**Issue by nanoric** [msys2/msys2-installer#8]
Command:
```
COPY ./msys2 C:/TEMP/msys2
RUN C:\TEMP\msys2\msys2-x86_64-20200602.exe --platform minimal --script auto-install.js
```

Error:
```
Step 9/33 : RUN C:\TEMP\msys2\msys2-x86_64-20200602.exe --platform minimal
 ---> Running in 8f40a237133d
The command 'cmd /S /C C:\TEMP\msys2\msys2-x86_64-20200602.exe --platform minimal' returned a non-zero code: 3221225781
C:/Program Files/Docker/docker.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

It seems some dlls are missing. Is it possible to remove these dependency from the final executable?

**Comment by nanoric** [comment]
I have used qt ifw for other projects in docker with auto-install scripts. So maybe that is not a problem of qtifw.

**Comment by lazka** [comment]
Could it be that the docker image doesn't provide all DLLs a full Desktop Windows does?

Either way, you could used our self extracting archive instead of the installer.

**Comment by nanoric** [comment]
Ok, maybe its a problem of Docker image, or a problem of my image. Anyway, it's hard to figure out without digging deeper.
I'll try self extracting archive.
