### ISSUE TITLE
Installer looks broken with dark theme

### ISSUE THREAD

**Issue by 500-internal-server-error** [msys2/msys2-installer#84]
[Installer 2024-07-27](https://github.com/msys2/msys2-installer/releases/download/2024-07-27/msys2-x86_64-20240727.exe) looks broken with Windows' dark theme:

![image](https://github.com/user-attachments/assets/bbc43bc4-a054-4c85-8d52-83969c2a5489)

The previous [installer 2024-05-07](https://github.com/msys2/msys2-installer/releases/download/2024-05-07/msys2-x86_64-20240507.exe) looks fine, if a bit janky:

![image](https://github.com/user-attachments/assets/edde44ac-278a-4576-b123-1f725ba93f30)

Seems like the dark theme is only half-applied for some reason.

**Comment by hgdagon** [comment]
Same for me, but looks slightly different. Win11 with Dark Mode.
![colorsmsys2](https://github.com/user-attachments/assets/214b4267-8071-4385-bfc3-44be89b212b7)

**Comment by brunvonlope** [comment]
With the fix by #89 the installer looks nice on Dark mode but regressed to Windows XP style in Light mode 🤢

**Comment by brunvonlope** [comment]
Gray background, regardless what you choose to compare for sake of sarcarsm, is not used by the latest Win32 guidelines. Not all Win32 apps were updated by MS but all of the Vista-era up today don't use a grey background:

![image](https://github.com/user-attachments/assets/99eafc26-660e-494b-947a-0cc80615879b)

**Comment by lazka** [comment]
Sure, I agree, but it looks like it's broken in Qt (see https://bugreports.qt.io/browse/QTBUG-123853) and I'm not motivated to look into fixing it there.

If anyone wants to, feel free. Here is a minimal LLM generated example which shows the problem:

```c++
// c++ main.cpp $(pkg-config --cflags --libs Qt6Widgets)
// ./main.exe

#include <QApplication>
#include <QWizard>
#include <QWizardPage>
#include <QLabel>
#include <QVBoxLayout>

class SimplePage : public QWizardPage {
public:
    SimplePage(const QString& title, const QString& text, QWidget* parent = nullptr) 
        : QWizardPage(parent) 
    {
        setTitle(title);
        QLabel* label = new QLabel(text);
        QVBoxLayout* layout = new QVBoxLayout;
        layout->addWidget(label);
        setLayout(layout);
    }
};

int main(int argc, char *argv[]) {
    QApplication app(argc, argv);

    QWizard wizard;
    wizard.setWizardStyle(QWizard::AeroStyle);
    wizard.setWindowTitle("Simple Wizard Example");

    // Add pages to the wizard
    wizard.addPage(new SimplePage("Page 1", "This is the first page."));
    wizard.addPage(new SimplePage("Page 2", "This is the second page."));
    wizard.addPage(new SimplePage("Page 3", "This is the final page."));

    // Set some basic properties
    wizard.setOption(QWizard::HaveHelpButton, true);
    wizard.setMinimumSize(500, 300);

    wizard.show();
    return app.exec();
}
```

![image](https://github.com/user-attachments/assets/908db988-853b-4c3d-a847-7df822bac65c)
